from decouple import config

WEBHOOK_URL = config('WEBHOOK_PROD')
CATACOMBS_IMAGE_URL = config('CATACOMBS_IMAGE_URL')
ORKS_IMAGE_URL = config('ORKS_IMAGE_URL')
CLAN_BOSSES_IMAGE_URL = config('CLAN_BOSSES_IMAGE_URL')